In [2]:
# %pip install imblearn,optuna
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix,f1_score
from sklearn import metrics
from sklearn.neural_network import MLPClassifier

from imblearn.over_sampling import RandomOverSampler, SMOTE
from imblearn.under_sampling import RandomUnderSampler
from imblearn.combine import SMOTEENN
import optuna as op
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn import tree

In [4]:
# %pip install dill
import dill
dill.dump_session('env.db')

In [60]:
df = pd.read_csv("bank_seasons.csv")
df['y'].value_counts()
#imbalanced dataset

#split dataset
x=df.drop('y', axis=1)
y=df['y']
x_train, x_test, y_train, y_test = train_test_split(x,y,random_state=1,train_size=0.7)
print(x_train.shape)
#print(x_test.shape)

#balance dataset (SMOTE)
smote=SMOTE(random_state=1) 
x_train, y_train = smote.fit_resample(x_train,y_train)
print(y_train.value_counts())

ss = StandardScaler()
x_train = pd.DataFrame(ss.fit_transform(x_train),columns=x_train.columns)
x_test = pd.DataFrame(ss.transform(x_test),columns=x_test.columns)


(31647, 32)
0    27909
1    27909
Name: y, dtype: int64


## XGboost

In [ ]:
# install xgboost
# %pip install xgboost

In [6]:
from xgboost import XGBClassifier
xgb = XGBClassifier()

In [8]:
clf = make_pipeline(StandardScaler(),xgb)
clf.fit(x_train, y_train)
y_pred = clf.predict(x_train)

scores = metrics.accuracy_score(y_train,y_pred)
print("training acc ",scores)

y_pred1 = clf.predict(x_test)
scores1 = metrics.accuracy_score(y_test,y_pred1)
f11 = metrics.f1_score(y_test,y_pred1)
print("testing acc ",scores1)
print("testing f1 ",f11)
cm_1 = confusion_matrix(y_test, y_pred1, labels=[0,1]).ravel()
print(cm_1)
# recall = cm_1[0][0]/(cm_1[0][0]+cm_1[0][1])
recall = cm_1[3]/(cm_1[3]+cm_1[2])
print(recall)

training acc  0.9657995628650257
testing acc  0.8962695370097317
testing f1  0.5388397246804325
[11335   678   729   822]
0.5299806576402321


## Adaboost

In [29]:
from sklearn.ensemble import AdaBoostClassifier

In [30]:
adab = AdaBoostClassifier()
clf = make_pipeline(StandardScaler(),adab)
clf.fit(x_train, y_train)
y_pred = clf.predict(x_train)

scores = metrics.accuracy_score(y_train,y_pred)
print("training acc ",scores)

y_pred1 = clf.predict(x_test)
scores1 = metrics.accuracy_score(y_test,y_pred1)
f11 = metrics.f1_score(y_test,y_pred1)
print("testing acc ",scores1)
print("testing f1 ",f11)
cm_1 = confusion_matrix(y_test, y_pred1, labels=[0,1]).ravel()
print(cm_1)
# recall = cm_1[0][0]/(cm_1[0][0]+cm_1[0][1])
recall = cm_1[3]/(cm_1[3]+cm_1[2])
print(recall)

training acc  0.9227989840088721
testing acc  0.8751105868475376
testing f1  0.47748303516347934
[11096   873   821   774]
0.4852664576802508


## Bagging_KNN

In [11]:
from   sklearn.neighbors  import   KNeighborsClassifier 
from   sklearn.ensemble  import   BaggingClassifier 

In [14]:
bagg = BaggingClassifier(KNeighborsClassifier(), max_samples= 0.5, max_features=0.5)
clf = make_pipeline(StandardScaler(),bagg)
clf.fit(x_train, y_train)
y_pred = clf.predict(x_train)

scores = metrics.accuracy_score(y_train,y_pred)
print("training acc ",scores)

y_pred1 = clf.predict(x_test)
scores1 = metrics.accuracy_score(y_test,y_pred1)
f11 = metrics.f1_score(y_test,y_pred1)
print("testing acc ",scores1)
print("testing f1 ",f11)
cm_1 = confusion_matrix(y_test, y_pred1, labels=[0,1]).ravel()
print(cm_1)
# recall = cm_1[0][0]/(cm_1[0][0]+cm_1[0][1])
recall = cm_1[3]/(cm_1[3]+cm_1[2])
print(recall)

training acc  0.9482425024185747
testing acc  0.8852108522559717
testing f1  0.41750841750841744
[11449   564   993   558]
0.3597678916827853


## GaussianNB

In [15]:
from   sklearn.naive_bayes  import   GaussianNB 

In [20]:
gnb = GaussianNB()
clf = make_pipeline(StandardScaler(),gnb)
clf.fit(x_train, y_train)
y_pred = clf.predict(x_train)

scores = metrics.accuracy_score(y_train,y_pred)
print("training acc ",scores)

y_pred1 = clf.predict(x_test)
scores1 = metrics.accuracy_score(y_test,y_pred1)
f11 = metrics.f1_score(y_test,y_pred1)
print("testing acc ",scores1)
print("testing f1 ",f11)
cm_1 = confusion_matrix(y_test, y_pred1, labels=[0,1]).ravel()
print(cm_1)
# recall = cm_1[0][0]/(cm_1[0][0]+cm_1[0][1])
recall = cm_1[3]/(cm_1[3]+cm_1[2])
print(recall)

training acc  0.8283349457164355
testing acc  0.7402683574166913
testing f1  0.2869864399919045
[9332 2681  842  709]
0.4571244358478401


## Discriminant_analysis

In [21]:
from   sklearn.discriminant_analysis  import   QuadraticDiscriminantAnalysis 

In [22]:
da = QuadraticDiscriminantAnalysis()
clf = make_pipeline(StandardScaler(),da)
clf.fit(x_train, y_train)
y_pred = clf.predict(x_train)

scores = metrics.accuracy_score(y_train,y_pred)
print("training acc ",scores)

y_pred1 = clf.predict(x_test)
scores1 = metrics.accuracy_score(y_test,y_pred1)
f11 = metrics.f1_score(y_test,y_pred1)
print("testing acc ",scores1)
print("testing f1 ",f11)
cm_1 = confusion_matrix(y_test, y_pred1, labels=[0,1]).ravel()
print(cm_1)
# recall = cm_1[0][0]/(cm_1[0][0]+cm_1[0][1])
recall = cm_1[3]/(cm_1[3]+cm_1[2])
print(recall)

training acc  0.8843921315704611
testing acc  0.81664700678266
testing f1  0.32729239924262915
[10472  1541   946   605]
0.3900709219858156


## GBDT

In [31]:
from   sklearn.ensemble  import   GradientBoostingClassifier 

In [38]:
gbdt = GradientBoostingClassifier()
clf = make_pipeline(StandardScaler(),gbdt)
clf.fit(x_train, y_train)
y_pred = clf.predict(x_train)

scores = metrics.accuracy_score(y_train,y_pred)
print("training acc ",scores)

y_pred1 = clf.predict(x_test)
scores1 = metrics.accuracy_score(y_test,y_pred1)
f11 = metrics.f1_score(y_test,y_pred1)
print("testing acc =",scores1)
print("testing f1 =",f11)
cm_1 = confusion_matrix(y_test, y_pred1, labels=[0,1]).ravel()
print("c m =",cm_1)
# recall = cm_1[0][0]/(cm_1[0][0]+cm_1[0][1])
recall = cm_1[3]/(cm_1[3]+cm_1[2])
print("recall =", recall)

training acc  0.9231789028628757
testing acc = 0.8815246240047184
testing f1 = 0.5195814648729448
confusion matrix = [11088   925   682   869]
recall = 0.5602836879432624


## Voting

In [58]:
from sklearn.ensemble import GradientBoostingClassifier, VotingClassifier, RandomForestClassifier 
import xgboost 
from sklearn.linear_model import LogisticRegression 
from sklearn.naive_bayes import GaussianNB 
from sklearn.linear_model import SGDClassifier

In [61]:
clf1 = GradientBoostingClassifier(n_estimators = 200 ) 
clf2 = RandomForestClassifier(random_state = 0 , n_estimators = 500 ) 
clf3 = LogisticRegression(random_state=1) 
clf4 = GaussianNB() 
clf5 = xgboost.XGBClassifier() 
clf6 = SGDClassifier(loss="modified_huber", penalty="l2", max_iter=5)
clf  = VotingClassifier(estimators = [ ('gbdt',clf1), 
        #   ( 'rf' ,clf2), 
         # ('lr',clf3), 
         #('nb',clf4), 
          ('xgboost',clf5),
        #   ('SGDClassifier',clf6) 
      ], 
          voting = 'soft' 
      )  
clf.fit(x_train, y_train)
y_pred = clf.predict(x_train)

scores = metrics.accuracy_score(y_train,y_pred)
print("training acc ",scores)

y_pred1 = clf.predict(x_test)
scores1 = metrics.accuracy_score(y_test,y_pred1)
f11 = metrics.f1_score(y_test,y_pred1)
print("testing acc =",scores1)
print("testing f1 =",f11)
cm_1 = confusion_matrix(y_test, y_pred1, labels=[0,1]).ravel()
print("confusion matrix =",cm_1)
# recall = cm_1[0][0]/(cm_1[0][0]+cm_1[0][1])
recall = cm_1[3]/(cm_1[3]+cm_1[2])
print("recall =", recall)

training acc  0.955050342183525
testing acc = 0.8970067826599823
testing f1 = 0.5459863503412415
confusion matrix = [11327   686   711   840]
recall = 0.5415860735009671


## SVM

In [ ]:
#SVM #SVM change parameters kernel='rbf'  the best
clf = make_pipeline(StandardScaler(),SVC(gamma='auto'))
clf.fit(x_train, y_train)
y_pred = clf.predict(x_train)

scores = metrics.accuracy_score(y_train,y_pred)
print("training acc ",scores)

y_pred1 = clf.predict(x_test)
scores1 = metrics.accuracy_score(y_test,y_pred1)
f11 = metrics.f1_score(y_test,y_pred1)
print("testing acc ",scores1)
print("testing f1 ",f11)
cm_1 = confusion_matrix(y_test, y_pred1, labels=[0,1]).ravel()
print(cm_1)
# recall = cm_1[0][0]/(cm_1[0][0]+cm_1[0][1])
recall = cm_1[3]/(cm_1[3]+cm_1[2])
print(recall)


In [ ]:
#SVM change parameters kernel='linear'
clf = make_pipeline(StandardScaler(),SVC(C=1.0, kernel='linear', degree=3, gamma='scale', coef0=0.0, shrinking=True, 
                                         probability=False, tol=0.001, cache_size=200, class_weight=None, verbose=False, 
                                         max_iter=-1, decision_function_shape='ovr', break_ties=False, random_state=None))
clf.fit(x_train, y_train)
y_pred = clf.predict(x_train)

scores = metrics.accuracy_score(y_train,y_pred)
print("training acc ",scores)

y_pred1 = clf.predict(x_test)
scores1 = metrics.accuracy_score(y_test,y_pred1)
f11 = metrics.f1_score(y_test,y_pred1)
print("testing acc ",scores1)
print("testing f1 ",f11)
cm_1 = confusion_matrix(y_test, y_pred1, labels=[0,1]).ravel()
print(cm_1)
# recall = cm_1[0][0]/(cm_1[0][0]+cm_1[0][1])
recall = cm_1[3]/(cm_1[3]+cm_1[2])
print(recall)

In [ ]:
#SVM change parameters kernel='poly'
clf = make_pipeline(StandardScaler(),SVC(C=1.0, kernel='poly', degree=3, gamma='scale', coef0=0.0, shrinking=True, 
                                         probability=False, tol=0.001, cache_size=200, class_weight=None, verbose=False, 
                                         max_iter=-1, decision_function_shape='ovr', break_ties=False, random_state=None))
clf.fit(x_train, y_train)
y_pred = clf.predict(x_train)

scores = metrics.accuracy_score(y_train,y_pred)
print("training acc ",scores)

y_pred1 = clf.predict(x_test)
scores1 = metrics.accuracy_score(y_test,y_pred1)
f11 = metrics.f1_score(y_test,y_pred1)
print("testing acc ",scores1)
print("testing f1 ",f11)
cm_1 = confusion_matrix(y_test, y_pred1, labels=[0,1]).ravel()
print(cm_1)
# recall = cm_1[0][0]/(cm_1[0][0]+cm_1[0][1])
recall = cm_1[3]/(cm_1[3]+cm_1[2])
print(recall)

In [ ]:
#SVM change parameters kernel='sigmoid'
clf = make_pipeline(StandardScaler(),SVC(C=1.0, kernel='sigmoid', degree=3, gamma='scale', coef0=0.0, shrinking=True, 
                                         probability=False, tol=0.001, cache_size=200, class_weight=None, verbose=False, 
                                         max_iter=-1, decision_function_shape='ovr', break_ties=False, random_state=None))
clf.fit(x_train, y_train)
y_pred = clf.predict(x_train)

scores = metrics.accuracy_score(y_train,y_pred)
print("training acc ",scores)

y_pred1 = clf.predict(x_test)
scores1 = metrics.accuracy_score(y_test,y_pred1)
f11 = metrics.f1_score(y_test,y_pred1)
print("testing acc ",scores1)
print("testing f1 ",f11)
cm_1 = confusion_matrix(y_test, y_pred1, labels=[0,1]).ravel()
print(cm_1)
# recall = cm_1[0][0]/(cm_1[0][0]+cm_1[0][1])
recall = cm_1[3]/(cm_1[3]+cm_1[2])
print(recall)

In [ ]:
#SVM change parameters kernel='sigmoid'
clf = make_pipeline(StandardScaler(),SVC(C=1.0, kernel='sigmoid', degree=3, gamma='scale', coef0=0.0, shrinking=True, 
                                         probability=False, tol=0.001, cache_size=200, class_weight=None, verbose=False, 
                                         max_iter=-1, decision_function_shape='ovr', break_ties=False, random_state=None))
clf.fit(x_train, y_train)
y_pred = clf.predict(x_train)

scores = metrics.accuracy_score(y_train,y_pred)
print("training acc ",scores)

y_pred1 = clf.predict(x_test)
scores1 = metrics.accuracy_score(y_test,y_pred1)
f11 = metrics.f1_score(y_test,y_pred1)
print("testing acc ",scores1)
print("testing f1 ",f11)
cm_1 = confusion_matrix(y_test, y_pred1, labels=[0,1]).ravel()
print(cm_1)
# recall = cm_1[0][0]/(cm_1[0][0]+cm_1[0][1])
recall = cm_1[3]/(cm_1[3]+cm_1[2])
print(recall)

Decision Tree

In [ ]:
#Decision Tree
clf = make_pipeline(StandardScaler(),tree.DecisionTreeClassifier())
clf.fit(x_train, y_train)
y_pred = clf.predict(x_train)

scores = metrics.accuracy_score(y_train,y_pred)
print("training acc ",scores)

y_pred1 = clf.predict(x_test)
scores1 = metrics.accuracy_score(y_test,y_pred1)
f11 = metrics.f1_score(y_test,y_pred1)
print("testing acc ",scores1)
print("testing f1 ",f11)
cm_1 = confusion_matrix(y_test, y_pred1, labels=[0,1]).ravel()
print(cm_1)
# recall = cm_1[0][0]/(cm_1[0][0]+cm_1[0][1])
recall = cm_1[3]/(cm_1[3]+cm_1[2])
print(recall)


SGDClassifier

        - 'hinge' gives a linear SVM.
        - 'log_loss' gives logistic regression, a probabilistic classifier.
        - 'modified_huber' is another smooth loss that brings tolerance to
           outliers as well as probability estimates.
        - 'squared_hinge' is like hinge but is quadratically penalized.
        - 'perceptron' is the linear loss used by the perceptron algorithm.
        - The other losses, 'squared_error', 'huber', 'epsilon_insensitive' and
          'squared_epsilon_insensitive' are designed for regression but can be useful
          in classification as well; see
          :class:`~sklearn.linear_model.SGDRegressor` for a description.


In [ ]:
from sklearn.linear_model import SGDClassifier

clf =  SGDClassifier(loss="hinge", penalty="l2", max_iter=5)
clf.fit(x_train, y_train)
y_pred = clf.predict(x_train)

scores = metrics.accuracy_score(y_train,y_pred)
print("training acc ",scores)

y_pred1 = clf.predict(x_test)
scores1 = metrics.accuracy_score(y_test,y_pred1)
f11 = metrics.f1_score(y_test,y_pred1)
print("testing acc ",scores1)
print("testing f1 ",f11)
cm_1 = confusion_matrix(y_test, y_pred1, labels=[0,1]).ravel()
print(cm_1)
# recall = cm_1[0][0]/(cm_1[0][0]+cm_1[0][1])
recall = cm_1[3]/(cm_1[3]+cm_1[2])
print(recall)


In [ ]:
from sklearn.linear_model import SGDClassifier

clf =  SGDClassifier(loss="huber", penalty="l2", max_iter=5)
clf.fit(x_train, y_train)
y_pred = clf.predict(x_train)

scores = metrics.accuracy_score(y_train,y_pred)
print("training acc ",scores)

y_pred1 = clf.predict(x_test)
scores1 = metrics.accuracy_score(y_test,y_pred1)
f11 = metrics.f1_score(y_test,y_pred1)
print("testing acc ",scores1)
print("testing f1 ",f11)
cm_1 = confusion_matrix(y_test, y_pred1, labels=[0,1]).ravel()
print(cm_1)
# recall = cm_1[0][0]/(cm_1[0][0]+cm_1[0][1])
recall = cm_1[3]/(cm_1[3]+cm_1[2])
print(recall)

In [54]:
from sklearn.linear_model import SGDClassifier

clf =  SGDClassifier(loss="modified_huber", penalty="l2", max_iter=5)
clf.fit(x_train, y_train)
y_pred = clf.predict(x_train)

scores = metrics.accuracy_score(y_train,y_pred)
print("training acc ",scores)

y_pred1 = clf.predict(x_test)
scores1 = metrics.accuracy_score(y_test,y_pred1)
f11 = metrics.f1_score(y_test,y_pred1)
print("testing acc ",scores1)
print("testing f1 ",f11)
cm_1 = confusion_matrix(y_test, y_pred1, labels=[0,1]).ravel()
print(cm_1)
# recall = cm_1[0][0]/(cm_1[0][0]+cm_1[0][1])
recall = cm_1[3]/(cm_1[3]+cm_1[2])
print(recall)

training acc  0.8946755526890967
testing acc  0.8319079917428487
testing f1  0.3893947509373326
[10557  1456   824   727]
0.4687298517085751


/Volumes/ExternalDisk/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_stochastic_gradient.py:705: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(


KN neighbor

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
clf =   KNeighborsClassifier(n_neighbors=100)
clf.fit(x_train, y_train)
y_pred = clf.predict(x_train)

scores = metrics.accuracy_score(y_train,y_pred)
print("training acc ",scores)

y_pred1 = clf.predict(x_test)
scores1 = metrics.accuracy_score(y_test,y_pred1)
f11 = metrics.f1_score(y_test,y_pred1)
print("testing acc ",scores1)
print("testing f1 ",f11)

cm_1 = confusion_matrix(y_test, y_pred1, labels=[0,1]).ravel()
print(cm_1)
# recall = cm_1[0][0]/(cm_1[0][0]+cm_1[0][1])
recall = cm_1[3]/(cm_1[3]+cm_1[2])
print(recall)


In [ ]:

model_mlp = MLPClassifier(max_iter=99999999,alpha = 0.01,hidden_layer_sizes=(128,65,35,16,8),learning_rate= 'adaptive',solver='adam',batch_size=64)
model_mlp.fit(x_train,y_train)

y_pred = model_mlp.predict(x_train)

scores = metrics.accuracy_score(y_train,y_pred)
print("training acc ",scores)

y_pred1 = model_mlp.predict(x_test)
scores1 = metrics.accuracy_score(y_test,y_pred1)
f11 = metrics.f1_score(y_test,y_pred1)
print("testing acc ",scores1)
print("testing f1 ",f11)


In [ ]:

if model_mlp.solver == 'sgd' or model_mlp.solver=='adam':
    plt.figure(figsize=(5,5))
    plt.plot(model_mlp.loss_curve_)
    plt.xlabel("iters")
    plt.ylabel(model_mlp.loss)
    plt.grid()
    plt.show()

In [ ]:
cm_1 = confusion_matrix(y_test, y_pred1, labels=[0,1]).ravel()
print(cm_1)
# recall = cm_1[0][0]/(cm_1[0][0]+cm_1[0][1])
recall = cm_1[3]/(cm_1[3]+cm_1[2])
print(recall)

In [ ]:
x_val = x_train[:1000]
y_val = y_train[:1000]
x_train = x_train[1000:]
y_train = y_train[1000:]

In [ ]:
import tensorflow as tf 
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(256, activation='relu', input_shape=(32,)),
    tf.keras.layers.Dropout(0.4),
    tf.keras.layers.Dense(64, activation='relu',input_shape=(32,)),
    tf.keras.layers.Dropout(0.4),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dropout(0.4),
    tf.keras.layers.Dense(16, activation='relu'),
    tf.keras.layers.Dropout(0.4),
    tf.keras.layers.Dense(8, activation='relu'),
    #tf.keras.layers.Dropout(0.4),
    tf.keras.layers.Dense(4, activation='relu'),
    #tf.keras.layers.Dropout(0.4), 
    tf.keras.layers.Dense(1, activation='sigmoid')
])

from keras import backend as K
def f1(y_true, y_pred):
    
    true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
    possible_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
    SVMSMOTEpredicted_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
    recall = true_positives / (possible_positives + K.epsilon())
    precision = true_positives / (predicted_positives + K.epsilon())
    f1 = 2*(precision*recall)/(precision+recall+K.epsilon())
    return f1

#model.compile(loss='binary_crossentropy', optimizer= "rmsprop", metrics=['accuracy'])
model.compile(loss='binary_crossentropy', optimizer= "rmsprop", metrics=[f1,'accuracy','AUC'])
history = model.fit(x_train, y_train, epochs=200,shuffle=True, validation_data=(x_val,y_val),batch_size=64)

In [ ]:
y_pred2 = model.predict(x_test)
y_pred2[y_pred2>0.5]=1
y_pred2[y_pred2<0.5]=0
scores2 = metrics.accuracy_score(y_test,y_pred2)
print("testing acc ",scores2)
model.evaluate(x_test,y_test)


In [ ]:
cm_2 = confusion_matrix(y_test, y_pred2, labels=[0,1])
print(cm_2)

In [ ]:
loss_values = history.history['loss']
val_loss_values = history.history['val_loss']
epochs = range(1, len(loss_values) + 1)

# val_1 = {"epochs": epochs, "val_loss": val_loss_values}
# val_pd_1 = pd.DataFrame(val_1)
# val_pd_1["val_loss"].min() # find the epochs with the minimum validation loss
# print(val_pd_1[val_pd_1["val_loss"] == val_pd_1["val_loss"].min()]) 

#Visulization of validation loss
plt.plot(epochs, loss_values,color = 'lightseagreen', label='Training loss')
plt.plot(epochs, val_loss_values,color = 'lightcoral', label='Validation loss')
plt.title('Training and validation loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.grid()
plt.legend()

In [ ]:
#Validation accuracy
# acc = history.history['accuracy']
# val_acc = history.history['val_accuracy']
acc = history.history['f1']
val_acc = history.history['val_f1']

# val_2 = {"epochs": epochs, "val_acc": val_acc}
# val_pd_2 = pd.DataFrame(val_2)
# val_pd_2["val_acc"].max() # find the epochs with the maximum accuracy
# print(val_pd_2[val_pd_2["val_acc"] == val_pd_2["val_acc"].max()]) 

#Visulization of accuracy
plt.plot(epochs, acc,color = 'lightseagreen', label='Training accuracy')
plt.plot(epochs, val_acc,color = 'lightcoral', label='Validation accuracy')
plt.title('Training and validation accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.grid()
plt.legend()